##Take the Dataframes

In [18]:
import pandas as pd
df1 = pd.read_csv("Reviews.csv")

df1.columns = ['Rating','Review']
df1 = df1.sort_index()
df1

        Rating                                             Review
0            1                3 yıldır kullanıyorum ve memnunum:)
1            1                      3 yıldır kullanıyorum müthiş
2            1  Ürün bugün elime geçti çok fazla inceleme fırs...
3            1  Almaya karar verdim. Hemencecik geldi. Keyifle...
4            1  Günlük kullanımınızı çok çok iyi karsılıyor kı...
...        ...                                                ...
243492       1                                fiyatına göre güzel
243493       1  Ürün kullanışlı iş görüyor fazlasıyla eşime al...
243494       1                            Hızlı Kargo, güzel ürün
243495       1  telefon başarılı hızlı bir cihaz  sadece beyaz...
243496       1  Urun cok guzel pazar gunu siparis verdim adana...

[243497 rows x 2 columns]

In [19]:
df2 = pd.read_csv("kenaryaziBasliklari.csv")
df2

,ID,Author,Title,Date,Gazette,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,1.0,Emre Kongar,Sumsare: Rüşvet ve hırsızlık üzerine,5.12.2017,Cumhuriyet Newspaper,NaN,NaN,NaN,NaN
1,3.0,MEHMED ŞEVKET EYGİ,Haysiyetli ve Vasıflı Müslüman Olmak İçin,5.12.2017,National Newspaper,NaN,NaN,NaN,NaN
2,4.0,Güray Öz,‘Vay Peşlerine mi Takıldın!’,6.12.2017,Cumhuriyet Newspaper,NaN,NaN,NaN,NaN
3,5.0,Güray Öz,‘Pelikan Yayıncılığı’ İşe Yarar mı?,4.12.2017,Cumhuriyet Newspaper,NaN,NaN,NaN,NaN
4,6.0,Güray Öz,Akademi Direniyor,3.12.2017,Cumhuriyet Newspaper,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
397,399.0,NUR ÇİNTAY,Şefkatli güç: Gastronomi,12.11.2017,Morning Newspaper,NaN,NaN,NaN,NaN
398,400.0,NUR ÇİNTAY,Efsane tren yolculukları,12.11.2017,Morning Newspaper,NaN,NaN,NaN,NaN
399,401.0,NUR ÇİNTAY,Son dakikacılar buraya!,11.11.2017,Morning Newspaper,NaN,NaN,NaN,NaN
400,402.0,NUR ÇİNTAY,Hayata Sarıl Lokantası,5.11.2017,Morning Newspaper,NaN,NaN,NaN,NaN
401,403.0,NUR ÇİNTAY,Üç patetik vaka,4.11.2017,Morning Newspaper,NaN,NaN,NaN,NaN

In [20]:
second_list = []
import math

for i in range(len(df2["Title"])):
    if(type(df2["Title"][i]) == str):
        second_list.append(df2["Title"][i])

In [21]:
df3 = pd.read_json("yemekisimleri.json", orient='columns')
df3

,Ingredient,Recipe
-MbOe68lzoof-uUREmkh,"{'Calorie': '278.6', 'Carbohydrates': '0.0', '...",NaN
-MbOe73ue8N4_3LE_KG8,"{'Calorie': '44.7', 'Carbohydrates': '10.1', '...",NaN
-MbOe8-SnHcXXuDvn-7o,"{'Calorie': '144.8', 'Carbohydrates': '32.5', ...",NaN
-MbOe8vlmbqQtNO2OvXN,"{'Calorie': '147.0', 'Carbohydrates': '0.7', '...",NaN
-MbOe9rTJr7aNiXBKCyp,"{'Calorie': '0.0', 'Carbohydrates': '0.0', 'Ch...",NaN
...,...,...
-MbO0d3kZ7fsHXY90Iyu,NaN,"{'CategoryBread': 'TATLI TARİFLERİ', 'Cuisine'..."
-MbO0dC-onmqfiEl9CCc,NaN,"{'CategoryBread': 'HAMUR İŞİ TARİFLERİ', 'Cuis..."
-MbO0dJMehgLQ12cVts0,NaN,"{'CategoryBread': 'ÇORBA TARİFLERİ', 'Cuisine'..."
-MbO0dU6m4e1pZ-AaSkM,NaN,"{'CategoryBread': 'KAHVALTILIK TARİFLERİ', 'Cu..."
-MbO0dfsCTvWimLVaXpM,NaN,"{'CategoryBread': 'ATIŞTIRMALIK TARİFLERİ', 'C..."

In [22]:
yemekisimleri = []

for i in range(len(df3["Recipe"])):
    try:
        math.isnan(df3["Recipe"][i])
    except:
        yemekisimleri.append(df3["Recipe"][i]["Name"])

##Combine the Dataframes

In [23]:
first_list = df1["Review"][:1000]

listofZeros = [0] * len(first_list)
listofOnes = [1] * len(second_list)
listofTwos = [2] * len(yemekisimleri)

In [24]:
sumnameList = []
sumnumberList = []

sumnameList.extend(first_list)
sumnameList.extend(second_list)
sumnameList.extend(yemekisimleri)

sumnumberList.extend(listofZeros)
sumnumberList.extend(listofOnes)
sumnumberList.extend(listofTwos)

Clean the Texts

Cleaning the new Dataframe

In [25]:
import re
import string

def text_temizle1(text):
    #kucuk harf yap
    text = text.lower()
    #parantez içindeki yazıları sil
    text = re.sub('\[.*?\]', '', text)
    #noktalama işaretlerini sil
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    #sayıları sil
    text = re.sub('\w*\d\w*', '', text)
    #3 karakterden kısa olan sözcükleri sil türkçe karakterlerle birlikte
    text = re.sub(r'\b[a-zğüşöçıİĞÜŞÖÇ]{1,2}\b', r'',text)
    return text

In [26]:
text_clean = []

for text in sumnameList:
    text_clean.append(text_temizle1(text))

Dataframeyi Kaydet

In [27]:
from pandas import DataFrame
dfClean = DataFrame({'Texts':text_clean,'Type':sumnumberList})

In [29]:
dfClean.to_csv("dfNew.csv")